const db=require('../database/db');
const base='SELECT id,name,address,latitude,longitude,radius_meters,status,is_default,created_at,updated_at FROM branch_locations';
function toApi(r){if(!r)return null;return {id:r.id,name:r.name,address:r.address||'',latitude:Number(r.latitude),longitude:Number(r.longitude),radiusMeters:Number(r.radius_meters),status:r.status,isDefault:!!r.is_default,createdAt:r.created_at,updatedAt:r.updated_at};}
async function listBranches(){return (await db.all(`${base} ORDER BY is_default DESC, name`)).map(toApi);}
async function getBranch(id){return toApi(await db.get(`${base} WHERE id=?`,[Number(id)]));}
async function getDefaultBranch(){return toApi(await db.get(`${base} WHERE is_default=1 ORDER BY id LIMIT 1`));}
async function getActiveBranch(id){const b=await getBranch(id);return b&&b.status==='Active'?b:null;}
function validate(i,e){const name=String(i.name??e?.name??'').trim(),address=String(i.address??e?.address??'').trim(),latitude=Number(i.latitude??e?.latitude),longitude=Number(i.longitude??e?.longitude),radiusMeters=Number(i.radiusMeters??e?.radiusMeters??100);if(!name)throw Object.assign(new Error('Branch name is required.'),{status:400});if(!Number.isFinite(latitude)||latitude<-90||latitude>90)throw Object.assign(new Error('A valid latitude is required.'),{status:400});if(!Number.isFinite(longitude)||longitude<-180||longitude>180)throw Object.assign(new Error('A valid longitude is required.'),{status:400});if(!Number.isFinite(radiusMeters)||radiusMeters<=0)throw Object.assign(new Error('Radius must be greater than zero.'),{status:400});return{name,address,latitude,longitude,radiusMeters};}
async function createBranch(i){const v=validate(i),now=Date.now();const sql=db.isPostgres?'INSERT INTO branch_locations(name,address,latitude,longitude,radius_meters,status,is_default,created_at,updated_at) VALUES (?,?,?,?,?,?,0,?,?) RETURNING id':'INSERT INTO branch_locations(name,address,latitude,longitude,radius_meters,status,is_default,created_at,updated_at) VALUES (?,?,?,?,?,?,0,?,?)';const r=await db.run(sql,[v.name,v.address,v.latitude,v.longitude,v.radiusMeters,i.status==='Inactive'?'Inactive':'Active',now,now]);return getBranch(r.lastInsertRowid);}
async function updateBranch(id,i){const existing=await db.get('SELECT * FROM branch_locations WHERE id=?',[Number(id)]);if(!existing)throw Object.assign(new Error('Branch not found.'),{status:404});const v=validate(i,toApi(existing)),status=i.status==null?existing.status:(i.status==='Inactive'?'Inactive':'Active');if(status==='Inactive'&&existing.status==='Active'&&(await db.get("SELECT COUNT(*) c FROM branch_locations WHERE status='Active'")).c<=1)throw Object.assign(new Error('At least one branch must remain active.'),{status:409});await db.run('UPDATE branch_locations SET name=?,address=?,latitude=?,longitude=?,radius_meters=?,status=?,updated_at=? WHERE id=?',[v.name,v.address,v.latitude,v.longitude,v.radiusMeters,status,Date.now(),Number(id)]);return getBranch(id);}
async function deleteBranch(id){const b=await db.get('SELECT * FROM branch_locations WHERE id=?',[Number(id)]);if(!b)throw Object.assign(new Error('Branch not found.'),{status:404});if((await db.get('SELECT COUNT(*) c FROM employees WHERE branch_id=?',[Number(id)])).c)throw Object.assign(new Error('Reassign employees before deleting this branch.'),{status:409});if((await db.get('SELECT COUNT(*) c FROM branch_locations')).c<=1)throw Object.assign(new Error('The last branch cannot be deleted.'),{status:409});if(b.status==='Active'&&(await db.get("SELECT COUNT(*) c FROM branch_locations WHERE status='Active'")).c<=1)throw Object.assign(new Error('At least one branch must remain active.'),{status:409});if(b.is_default){const r=await db.get("SELECT id FROM branch_locations WHERE id<>? ORDER BY status='Active' DESC,id LIMIT 1",[Number(id)]);await db.run('UPDATE branch_locations SET is_default=1 WHERE id=?',[r.id]);}await db.run('DELETE FROM branch_locations WHERE id=?',[Number(id)]);}
module.exports={listBranches,getBranch,getDefaultBranch,getActiveBranch,createBranch,updateBranch,deleteBranch,toApi};
