const db=require('../database/db');const branches=require('./branchService');
const select=`SELECT e.*,b.name branch_name,b.status branch_status FROM employees e LEFT JOIN branch_locations b ON b.id=e.branch_id`;
function toApi(r){if(!r)return null;return{id:r.id,name:r.name,department:r.department,designation:r.designation,phone:r.phone,email:r.email,status:r.status,branchId:r.branch_id,branchName:r.branch_name||'',branchStatus:r.branch_status||null};}
async function listEmployees(){return(await db.all(`${select} ORDER BY e.created_at ASC`)).map(toApi);}
async function findEmployee(id){return id?toApi(await db.get(`${select} WHERE e.id=?`,[String(id).toUpperCase()])):null;}
async function resolveBranch(id,allow=false){const b=id==null||id===''?(await branches.getActiveBranch((await branches.getDefaultBranch())?.id))||(await branches.listBranches()).find(x=>x.status==='Active'):(allow?await branches.getBranch(id):await branches.getActiveBranch(id));if(!b)throw Object.assign(new Error('An active branch is required.'),{status:400});return b;}
async function createEmployee(i){const clean=String(i.id).trim().toUpperCase();if(await findEmployee(clean))throw Object.assign(new Error('An employee with this ID already exists.'),{status:409});const now=Date.now(),b=await resolveBranch(i.branchId);await db.run('INSERT INTO employees(id,name,department,designation,phone,email,status,branch_id,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?)',[clean,String(i.name).trim(),(i.department||'').trim(),(i.designation||'').trim(),(i.phone||'').trim(),(i.email||'').trim(),i.status==='Inactive'?'Inactive':'Active',b.id,now,now]);return findEmployee(clean);}
async function updateEmployee(id,i){const old=await findEmployee(id);if(!old)throw Object.assign(new Error('Employee not found.'),{status:404});const b=await resolveBranch(i.branchId==null?old.branchId:i.branchId,i.branchId==null),v=[String(i.name??old.name).trim(),String(i.department??old.department??'').trim(),String(i.designation??old.designation??'').trim(),String(i.phone??old.phone??'').trim(),String(i.email??old.email??'').trim(),i.status==='Inactive'?'Inactive':'Active',b.id,Date.now(),old.id];await db.run('UPDATE employees SET name=?,department=?,designation=?,phone=?,email=?,status=?,branch_id=?,updated_at=? WHERE id=?',v);return findEmployee(old.id);}
async function deleteEmployee(id){await db.run('DELETE FROM employees WHERE id=?',[String(id).toUpperCase()]);}
module.exports={listEmployees,findEmployee,createEmployee,updateEmployee,deleteEmployee,toApi};
